apiVersion: v1
kind: ConfigMap
metadata:
  name: anythingllm-api-config
  namespace: anythingllm
  labels:
    app: anythingllm-api
    component: config
data:
  # API Configuration
  API_TITLE: "AnythingLLM API"
  API_VERSION: "1.0.0"
  API_PREFIX: "/api/v1"
  
  # Server Configuration
  HOST: "0.0.0.0"
  PORT: "8000"
  WORKERS: "1"
  
  # Storage Configuration
  STORAGE_TYPE: "local"
  STORAGE_PATH: "/app/uploads"
  MAX_FILE_SIZE: "104857600"  # 100MB
  ALLOWED_FILE_TYPES: "pdf,json,csv"
  
  # Security Configuration
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "60"
  API_KEY_HEADER: "X-API-Key"
  
  # Rate Limiting Configuration
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "3600"
  
  # Logging Configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  LOG_SANITIZE_SENSITIVE: "true"
  
  # Job Management Configuration
  JOB_CLEANUP_DAYS: "7"
  MAX_CONCURRENT_JOBS: "5"
  
  # Health Check Configuration
  HEALTH_CHECK_TIMEOUT: "10"
  
  # AnythingLLM Configuration (non-sensitive)
  ANYTHINGLLM_TIMEOUT: "30"
  
  # Redis Configuration (if enabled)
  REDIS_ENABLED: "false"