apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-api-uploads
  namespace: anythingllm
  labels:
    app: anythingllm-api
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-api-logs
  namespace: anythingllm
  labels:
    app: anythingllm-api
    component: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard