apiVersion: v1
kind: ServiceAccount
metadata:
  name: anythingllm-api
  namespace: anythingllm
  labels:
    app: anythingllm-api
    component: rbac
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: anythingllm-api-role
  namespace: anythingllm
  labels:
    app: anythingllm-api
    component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anythingllm-api-rolebinding
  namespace: anythingllm
  labels:
    app: anythingllm-api
    component: rbac
subjects:
- kind: ServiceAccount
  name: anythingllm-api
  namespace: anythingllm
roleRef:
  kind: Role
  name: anythingllm-api-role
  apiGroup: rbac.authorization.k8s.io