apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-anythingllm-config
  namespace: anythingllm
  labels:
    app: fluentd
    component: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/anythingllm-api-*.log
      pos_file /var/log/fluentd-anythingllm-api.log.pos
      tag kubernetes.anythingllm.api
      format json
      time_key timestamp
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </source>

    <filter kubernetes.anythingllm.api>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "#{ENV['KUBERNETES_SERVICE_HOST']}:#{ENV['KUBERNETES_SERVICE_PORT_HTTPS']}"
      verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || true}"
      ca_file "#{ENV['KUBERNETES_CA_FILE']}"
      skip_labels false
      skip_container_metadata false
      skip_master_url false
      skip_namespace_metadata false
    </filter>

    <filter kubernetes.anythingllm.api>
      @type record_transformer
      <record>
        service anythingllm-api
        environment "#{ENV['ENVIRONMENT'] || 'production'}"
        cluster "#{ENV['CLUSTER_NAME'] || 'default'}"
      </record>
    </filter>

    # Parse structured JSON logs
    <filter kubernetes.anythingllm.api>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type json
        time_key timestamp
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </filter>

    # Add correlation ID indexing
    <filter kubernetes.anythingllm.api>
      @type record_transformer
      <record>
        correlation_id ${record["correlation_id"] || "unknown"}
        request_id ${record["request_id"] || "unknown"}
        user_id ${record["user_id"] || "anonymous"}
      </record>
    </filter>

    # Route to different outputs based on log level
    <match kubernetes.anythingllm.api>
      @type copy
      <store>
        @type elasticsearch
        host "#{ENV['ELASTICSEARCH_HOST'] || 'elasticsearch'}"
        port "#{ENV['ELASTICSEARCH_PORT'] || '9200'}"
        index_name anythingllm-api-logs
        type_name _doc
        include_tag_key true
        tag_key @log_name
        flush_interval 10s
        <buffer>
          @type file
          path /var/log/fluentd-buffers/anythingllm-api.buffer
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 2
          flush_interval 5s
          retry_forever
          retry_max_interval 30
          chunk_limit_size 2M
          queue_limit_length 8
          overflow_action block
        </buffer>
      </store>
      <store>
        @type file
        path /var/log/anythingllm-api/access.log
        append true
        <format>
          @type json
        </format>
        <buffer>
          flush_mode interval
          flush_interval 30s
        </buffer>
      </store>
    </match>

    # Error logs to separate index
    <filter kubernetes.anythingllm.api>
      @type grep
      <regexp>
        key level
        pattern ^(ERROR|CRITICAL)$
      </regexp>
    </filter>

    <match kubernetes.anythingllm.api.error>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST'] || 'elasticsearch'}"
      port "#{ENV['ELASTICSEARCH_PORT'] || '9200'}"
      index_name anythingllm-api-errors
      type_name _doc
      include_tag_key true
      tag_key @log_name
      flush_interval 5s
    </match>